#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset
# Espera 5 minutos al backend antes de iniciar el frontend
>&2 echo 'Esperando que el backend esté disponible...'
wait-for-it "django:446" -t 300
>&2 echo 'Backend disponible, iniciando el frontend...'

exec nginx -g 'daemon off;'