#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30

>&2 echo 'PostgreSQL is available'

if [ -z "${REDIS_URL}" ]; then
  >&2 echo 'Error: REDIS_URL is not set'
  exit 1
fi

redis_host_port=$(echo "${REDIS_URL}" | sed -E 's/redis:\/\/([^:]+):([0-9]+)/\1:\2/')
wait-for-it "${redis_host_port}" -t 30

>&2 echo 'Redis is available'

exec "$@"
